### ISSUE TITLE
Replaying reassociate request failed on 5G

### ISSUE THREAD

**Issue by WeiXiaoQian** [vanhoefm/krackattacks-scripts#10]
I have tested successfully on my AP 2.4G follow your tools and WFA tool 👍 
then I try to test my AP 5G band FT vulnerable, follow your guide, everything is OK

The console show Replaying reassociate request all the time
I use sniffer to sniffing reassociate request, but I cannot see it, I can see it in 2.4G case.

This issue appeared on both AR9462 and Intel3165.

Thank you!

**Comment by vanhoefm** [comment]
Did you test whether you can inject frames in the 5 GHz band?

First set your device to monitor mode. Then set it to the channel that your 5 GHz device is on. For example, if your AP is on channel 36, use `sudo iw wlp0s20u1 set channel 36`. Then test injection using `aireplay-ng -9 -e network_name wlan0mon` where `network_name` is the name of the SSID.

**Comment by FancyQian** [comment]
I had used aireplay do inject attack, but both 2.4 and 5g result are same....   
```
~ iw wlan0mon set channel 6    
~ iw wlan0 set channel 6
~ sudo aireplay-ng -9 -e krack wlan0mon
14:02:44  Waiting for beacon frame (ESSID: krack) on channel 6
Found BSSID "1E:AB:C0:15:1F:F0" to given ESSID "krack".
14:02:44  Trying broadcast probe requests...
14:02:46  No Answer...
14:02:46  Found 1 AP 

14:02:46  Trying directed probe requests...
14:02:46  1E:AB:C0:15:1F:F0 - channel: 6 - 'krack'
14:02:52   0/30:   0%

~ iw wlan0mon set channel 36    
~ iw wlan0 set channel 36
~ sudo aireplay-ng -9 -e krack-5g wlan0mon
14:07:31  Waiting for beacon frame (ESSID: krack-5g) on channel 36
Found BSSID "1A:AB:C0:15:1F:F0" to given ESSID "krack-5g".
14:07:31  Trying broadcast probe requests...
14:07:33  No Answer...
14:07:33  Found 1 AP 

14:07:33  Trying directed probe requests...
14:07:33  1A:AB:C0:15:1F:F0 - channel: 36 - 'krack-5g'
14:07:39   0/30:   0%




```
Does 5G band work on your kali?

Thanks

**Comment by vanhoefm** [comment]
Unfortunately, 5 GHz is not supported. Supporting it likely requires manual patches to the Linux driver, for details see the [updated README](https://github.com/vanhoefm/krackattacks-scripts/blob/research/README.md#extra-5-ghz-not-supported).
