### ISSUE TITLE
L2Socket is Not defined  in the MitmSocket ???

### ISSUE THREAD

**Issue by DesenYang** [vanhoefm/krackattacks-scripts#2]
as the title

**Comment by moedje** [comment]
[krack.py.txt](https://github.com/vanhoefm/krackattacks-test-ap-ft/files/1404981/krack.py.txt)
I resolved this using L2dnetSocket as the class MitmSocket inherits and it runs not sure if it works correctly yet but I didn't see any L2Socket in Scapy but did find L2dnetSocket so hoping it works... This is the full line I changed 116.
class MitmSocket(L2dnetSocket): # old line: class MitmSocket(L2Socket):
Anyone know if this will work correctly or not?

**Comment by GrahamMThomas** [comment]
I replaced the line in my code, and it appears to be working for me.

**Comment by vanhoefm** [comment]
This is a strange bug. The updated script now loads a python environment with a specific version of Scapy, so hopefully this bug is now avoided.
