### ISSUE TITLE
Could not read interface flags: No such device

### ISSUE THREAD

**Issue by Sc0rpi** [vanhoefm/krackattacks-scripts#21]
Thanks for your hard work, it's amazing.
And I have a little question, I run the script and find the following messages:

~/krackattacks-test/krackattack$ sudo wpa_supplicant -D nl80211 -i wlan0 -c network.conf
Successfully initialized wpa_supplicant
Could not read interface wlan0 flags: No such device
nl80211: Driver does not support authentication/association or connect commands
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
Could not read interface wlan0 flags: No such device
wlan0: Failed to initialize driver interface

My network.conf file is as follow:
ctrl_interface=/var/run/wpa_supplicant
      network={
          ssid="Test"
          key_mgmt=FT-PSK
          psk="password"
      }

And "Test" is my target SSID.
Why I can't accomplish my attack?

**Comment by vanhoefm** [comment]
First learn how to use wpa_supplicant: https://wiki.archlinux.org/index.php/WPA_supplicant
