### ISSUE TITLE
krack-test-client.py not report result

### ISSUE THREAD

**Issue by Metori** [vanhoefm/krackattacks-scripts#22]
This script successfully starts Wi-Fi AP. Then I connecting my phone to it and can't get a result even after ~20 minutes.
Only a lot of lines like this:

> [15:34:10] 00:11:22:33:44:55: Hostapd: Resetting Tx IV of group key and sending Msg3/4

**Comment by vanhoefm** [comment]
Which test are you running? Is your client requesting an IP address?

**Comment by Metori** [comment]
This issue actual for all test that krack-test-client.py script runs (--group, --tptk and no args run). Yes, my client successfully gets an IP address.
Here is a full log: 
[krack-test-client_out.txt](https://github.com/vanhoefm/krackattacks-scripts/files/1473054/krack-test-client_out.txt)

**Comment by mikahe** [comment]
I'm seeing this too with 8812au based wifi nic. Most likely due to monitor interface not seeing any packets.

**Comment by Metori** [comment]
I'm using 8812au WiFi stick too.

**Comment by eits3rd** [comment]
How can I apply the monitor interface use to 8812au based wifi nic?

**Comment by jmyth742** [comment]
Hi, has there been any update on this? i am experiencing the same issue...thanks!

**Comment by vanhoefm** [comment]
Try using a different WiFi dongle to carry out the tests with.

**Comment by vanhoefm** [comment]
Closing due to old age.
