### ISSUE TITLE
ATTENTION: Someone maybe offense your copyright.

### ISSUE THREAD

**Issue by Sc0rpi** [vanhoefm/krackattacks-scripts#23]
Dear author:
I have read your paper in CSS 2017 and the source code in this repository. It's amazing.
Thanks for your sharing.
But I have find a serious probolem that there is a Chinese named NoahhhRyan and claimed that he is the only Chinese in your company to complety the project and put out a article in the most well-known chinese security web-site freebuf on how he reappear your work.
The github page of his project is https://github.com/NoahhhRyan/krackattacks-test and the article he put out in the most well-known Chinese security-website is www.freebuf.com/articles/wireless/153255.html.
Can you confirm that? Is he is really the only Chinese engineering in your company? Or he is just offense your Copyright.

**Comment by vanhoefm** [comment]
Note that redistributing my work is allowed, as long as appropriate credit is given to me. But I don't know NoahhhRyan at all. This person was not given the permission to redistribute my work as his own. So if he is redistributing my work as his own, he's violating the copyright.

**Comment by vanhoefm** [comment]
Closed due to no further responses
