### ISSUE TITLE
ft-script reassociates with AP in a loop

### ISSUE THREAD

**Issue by Jarlaxle1112** [vanhoefm/krackattacks-scripts#39]
OS: Kali

Wifi-Adapter: 
TP-Link TL-WN821N v3 / TL-WN822N v2 802.11n [Atheros AR7010+AR9287]
Ralink Technology, Corp. RT5572 Wireless Adapter
Intel Corporation PRO/Wireless 3945ABG [Golan]

unblocked wifi and disabled hwcrypto

created working network.conf

sudo wpa_supplicant -D nl80211 -i wlan0 -c network.conf
works as expected, the client connects to the AP. I can use wpa_cli to roam between the 2 APs. arping is working fine.

sudo ./krack-ft-test.py wpa_supplicant -D nl80211 -i wlan0 -c network.conf
client connects to first AP
arping works
If i use wpa_cli to roam to the second AP i get the following log:
Authenticated WLAN station
Reassociated WLAN station
Fast transition for WLAN station
Connected WLAN station
Completed handover for WLAN station
Reassociated WLAN station
Fast transition for WLAN station
Connected WLAN station
Reassociated WLAN station
Fast transition for WLAN station
Connected WLAN station
Reassociated WLAN station
...

of course arping is not working anymore
All 3 Wifi-Adapters show the same behaviour.

Is there a way to fix this?

**Comment by vanhoefm** [comment]
Closing due to old age.
