### ISSUE TITLE
make -j 2 not working

### ISSUE THREAD

**Issue by Izal99** [vanhoefm/krackattacks-scripts#44]
how to solve this? I tried to follow the instructions in > /krack-test-client.py --help >cp defconfig .config make -j 2 ,but ended up with this

root@authorized:~/krackattack/krackattack/hostapd# cp defconfig .config
root@authorized:~/krackattack/krackattack/hostapd# make -j 2
In file included from /root/krackattack/krackattack/src/utils/includes.h:19:0,
                 from main.c:9:
/root/krackattack/krackattack/src/utils/stdlib.h:33:10: fatal error: bits/wait.h: No such file or directory
 #include <bits/wait.h>
          ^~~~~~~~~~~~~
compilation terminated.
Makefile:1036: recipe for target 'main.o' failed
make: *** [main.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from /root/krackattack/krackattack/src/utils/includes.h:19:0,
                 from config_file.c:9:
/root/krackattack/krackattack/src/utils/stdlib.h:33:10: fatal error: bits/wait.h: No such file or directory
 #include <bits/wait.h>
          ^~~~~~~~~~~~~
compilation terminated.
Makefile:1036: recipe for target 'config_file.o' failed
make: *** [config_file.o] Error 1

**Comment by vanhoefm** [comment]
Closing due to age. Note that the script only works on Linux.
