### ISSUE TITLE
How to make AP work on 5GHz?

### ISSUE THREAD

**Issue by kalpittiwari** [vanhoefm/krackattacks-scripts#45]
I want to test my client which only connects to Access Points operating on 5GHz. Can I tweak the script to make AP work on 5GHz?

Thanks!

**Comment by kalpittiwari** [comment]
I modified the options in hostpad.conf. The error I am getting is same as #30

**Comment by YECharles** [comment]
I have the same problem. I think it is the problem of hostadp configuration. Is there any solution for that?

**Comment by vanhoefm** [comment]
Unfortunately, 5 GHz is not supported. Supporting it likely requires manual patches to the Linux driver, for details see the [updated README](https://github.com/vanhoefm/krackattacks-scripts/blob/research/README.md#extra-5-ghz-not-supported).
