### ISSUE TITLE
how to fix Successfully initialized wpa_supplicant  wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD wlan0: No network configuration found for the current AP

### ISSUE THREAD

**Issue by Mrvu182hp** [vanhoefm/krackattacks-scripts#51]
my save file network.conf

ctrl_interface=/var/run/wpa_supplicant
      network={
          ssid="MY TEST AP"
          key_mgmt=FT-PSK
          psk="123456789"
      }
i try use 

sudo wpa_supplicant -D nl80211 -i wlan0 -c network.conf
Successfully initialized wpa_supplicant
wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=b4:ee:b4:4c:1f:d4 reason=3 locally_generated=1
wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=b4:ee:b4:4c:1f:d4 reason=3 locally_generated=1
wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=b4:ee:b4:4c:1f:d4 reason=3 locally_generated=1
wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
............
my AP network test passwork 987654321.
i try use 123456789 login wifi not work please help me how to config for next step
thank a lot. @vanhoefm  @insp3ctre @DanRobinsonHPE

**Comment by vanhoefm** [comment]
Did you disable Wi-Fi in your network manager? Double check that there is no other instance of `wpa_supplicant` that is running.

**Comment by vanhoefm** [comment]
Closing as no further reply was received.
