### ISSUE TITLE
 wpa_supplicant unknown global field,  Invalid configuration line

### ISSUE THREAD

**Issue by gearcapitan** [vanhoefm/krackattacks-scripts#58]
Successfully initialized wpa_supplicant
Line 2: unknown global field 'network={{'.
Line 2: Invalid configuration line 'network={{'.
Line 3: unknown global field 'ssid="asdasd"'.
Line 3: Invalid configuration line 'ssid="asdasd"'.
Line 4: unknown global field 'key_mgmt=FT-PSK'.
Line 4: Invalid configuration line 'key_mgmt=FT-PSK'.
Line 5: unknown global field 'psk="123123"'.
Line 5: Invalid configuration line 'psk="123123"'.
Line 6: unknown global field '}}'.
Line 6: Invalid configuration line '}}'.
Failed to read or parse configuration '/root/krackattacks-scripts/krackattack/network.conf'.﻿

**Comment by giuliocomi** [comment]
You have to compile hostapd as explained in the setup instructions. This should solve this error

Da: Gearcapitan
Inviato: giovedì 10 maggio, 20:24
Oggetto: [vanhoefm/krackattacks-scripts] wpa_supplicant unknown global field, Invalid configuration line (#58)
A: vanhoefm/krackattacks-scripts
Cc: Subscribed


Successfully initialized wpa_supplicant
Line 2: unknown global field 'network={{'.
Line 2: Invalid configuration line 'network={{'.
Line 3: unknown global field 'ssid="asdasd"'.
Line 3: Invalid configuration line 'ssid="asdasd"'.
Line 4: unknown global field 'key_mgmt=FT-PSK'.
Line 4: Invalid configuration line 'key_mgmt=FT-PSK'.
Line 5: unknown global field 'psk="123123"'.
Line 5: Invalid configuration line 'psk="123123"'.
Line 6: unknown global field '}}'.
Line 6: Invalid configuration line '}}'.
Failed to read or parse configuration '/root/krackattacks-scripts/krackattack/network.conf'.﻿

**Comment by vanhoefm** [comment]
It seems there is a syntax error in the second line. Only include one opening and closing brace, so start with `network={` and end with just `}`.
