### ISSUE TITLE
ERROR: Virtual monitor interface doesn't seem to pass 802.11 encryption header to userland.

### ISSUE THREAD

**Issue by weiwu123** [vanhoefm/krackattacks-scripts#62]
How do I fix this? Does any one know about this error?
Thanks!

wlp1s0: CTRL-EVENT-DISCONNECTED bssid=f4:4e:05:10:8b:d0 reason=3 locally_generated=1
[16:35:38] Note: disable Wi-Fi in your network manager so it doesn't interfere with this script
nl80211: deinit ifname=wlp1s0 disabled_11b_rates=0
wlp1s0: CTRL-EVENT-TERMINATING 
Successfully initialized wpa_supplicant
wlp1s0: CTRL-EVENT-REGDOM-CHANGE init=BEACON_HINT type=UNKNOWN
wlp1s0: CTRL-EVENT-REGDOM-CHANGE init=BEACON_HINT type=UNKNOWN
wlp1s0: CTRL-EVENT-REGDOM-CHANGE init=BEACON_HINT type=UNKNOWN
wlp1s0: CTRL-EVENT-REGDOM-CHANGE init=BEACON_HINT type=UNKNOWN
wlp1s0: CTRL-EVENT-REGDOM-CHANGE init=BEACON_HINT type=UNKNOWN
wlp1s0: CTRL-EVENT-REGDOM-CHANGE init=BEACON_HINT type=UNKNOWN
wlp1s0: CTRL-EVENT-REGDOM-CHANGE init=BEACON_HINT type=UNKNOWN
wlp1s0: CTRL-EVENT-REGDOM-CHANGE init=BEACON_HINT type=UNKNOWN
wlp1s0: SME: Trying to authenticate with f4:4e:05:10:8b:d0 (SSID='test_ft' freq=2437 MHz)
[16:35:43] Detected Authentication frame, clearing client state
wlp1s0: Trying to associate with f4:4e:05:10:8b:d0 (SSID='test_ft' freq=2437 MHz)
[16:35:43] Detected normal association frame
wlp1s0: Associated with f4:4e:05:10:8b:d0
wlp1s0: CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
wlp1s0: CTRL-EVENT-REGDOM-CHANGE init=COUNTRY_IE type=COUNTRY alpha2=US
wlp1s0: WPA: Key negotiation completed with f4:4e:05:10:8b:d0 [PTK=CCMP GTK=CCMP]
wlp1s0: CTRL-EVENT-CONNECTED - Connection to f4:4e:05:10:8b:d0 completed [id=0 id_str=]
[16:35:43] ERROR: Virtual monitor interface doesn't seem to pass 802.11 encryption header to userland.

**Comment by vanhoefm** [comment]
Try disabling hardware encryption. If that doesn't help, get another Wi-Fi adapter.

**Comment by weiwu123** [comment]
I did run ./disable-hwcrypto.sh first, so I have no idea why this happened.
But anyway, I changed another Wi-Fi adapter and it's working fine.
Thanks.
