### ISSUE TITLE
Not able to execute ./krack-test-client.py file

### ISSUE THREAD

**Issue by HarikaSiddula** [vanhoefm/krackattacks-scripts#66]
When i am running ./krack-test-client.py file i am getting error as Invalid Syntax at "../wpaspy/wpaspy.py".
I have tried executing using python2, i am getting above error and as per github README file wpaspy.py file is written in python3. So i tried running through python3 i am getting error like scapy not available for python3.
Can you please suggest me on this issue. I am running on Ubuntu 16.04 machine

**Comment by vanhoefm** [comment]
Closed due to age. Note that version v1 only supported python2.
