### ISSUE TITLE
About replay-broadcast test

### ISSUE THREAD

**Issue by zixinniao** [vanhoefm/krackattacks-scripts#69]
Which patch should be updated on android 6.0 for the first test --replay-broadcast?

**Comment by Matheus-Garbelini** [comment]
@vanhoefm It's not clear which patch fix clients that replies to broadcast encrypted frames. I couldn't find anywhere this patch. Is this a known CVE or it was discovered alongside KRACK?

**Comment by vanhoefm** [comment]
This generally requires a driver patch (or firmware patch). For instance, it cannot be patched by updaing hostap or wpa_supplicant.
