### ISSUE TITLE
Hi:

### ISSUE THREAD

**Issue by Aiswarya-kk** [vanhoefm/krackattacks-scripts#70]
Hi:

This is a small guide to test your client wifi. I bought TL-WN722N v1 device but I will test it with anothers... I used Kali 2017.1.

1.- Install kali.

2.- Execute:

$ apt-get update
$ apt-get install libnl-3-dev libnl-genl-3-dev pkg-config libssl-dev net-tools git sysfsutils python-scapy python-pycryptodome

3.- Clone krack-attack scripts

$ git clone https://github.com/vanhoefm/krackattacks-scripts.git

4.- Compile hostapd:

$ cd krackattacks-scripts/krackattack
--> We are in "krackattacks-scripts/krackattack" directory
$ pwd
/root/krackattacks-scripts/krackattack
$ cd ../hostapd
$ cp defconfig .config
$ make -j 2

5.- Disable hardware network

$  cd ../krackattack/
$ chmod 777 disable-hwcrypto.sh
$ ./disable-hwcrypto.sh
$ rfkill unblock wifi
$ ifconfig wlan0mon down
$ ifconfig wlan0 down
$ nmcli networking off
$ reboot

6.- Test client:

$ python2 krack-test-client.py

--> It will be waiting for connections to his own ESSID. It is "testnetwork" and psk is "abcdefgh".
When you connect (with other device, not with this machine Kali 2017.1) the client you will see if your client has or hasnt the vulnerability in both, normal or group.

Best regards
Perico

_Originally posted by @PericoMele in https://github.com/vanhoefm/krackattacks-scripts/issues/32#issuecomment-351696993_

**Comment by Aiswarya-kk** [comment]
![IMG_20190730_131449](https://user-images.githubusercontent.com/53484324/62139957-c8695500-b307-11e9-830e-daff4773b23f.jpg)

I tried all the commands given by @PericoMele. But still it shows the same error "Disable Wi-Fi in network manager" (Attached the screenshot of error).Please help me to resolve this issue.

**Comment by kimocoder** [comment]
"service network-manager stop" ?

**Comment by vanhoefm** [comment]
Hopefully these extra instructions were useful to some! If there are suggestions to improve the README feel free to post them (or send a pull request).
