### ISSUE TITLE
krack-ft-test.py no output when generating traffic between AP and client

### ISSUE THREAD

**Issue by AnnabellBrocker** [vanhoefm/krackattacks-scripts#72]
I followed the instructions of the readme (Testing Access Points: Detecting a vulnerable FT Handshake (802.11r))
When I generate the traffic (sudo arping ....), I can see on the AP that it is receiving something (turned on traces). But the script krack-ft-test.py has no output for the traffic. 
That is the output so far:

sudo Downloads/krackattacks-scripts-research/krackattack/krack-ft-test.py wpa_supplicant -D nl80211 -i wlan0 -c Dokumente/network_krackattack.conf 
[08:27:13] Note: disable Wi-Fi in your network manager so it doesn't interfere with this script
Successfully initialized wpa_supplicant
wlan0: SME: Trying to authenticate with 00:a0:57:1e:39:49 (SSID='LCS-QM-AB-krackattack' freq=5180 MHz)
wlan0: Trying to associate with 00:a0:57:1e:39:49 (SSID='LCS-QM-AB-krackattack' freq=5180 MHz)
[08:27:17] Detected Authentication frame, clearing client state
[08:27:17] Detected Authentication frame, clearing client state
[08:27:17] Detected normal association frame
wlan0: Associated with 00:a0:57:1e:39:49
wlan0: CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
wlan0: WPA: Key negotiation completed with 00:a0:57:1e:39:49 [PTK=CCMP GTK=CCMP]
wlan0: CTRL-EVENT-CONNECTED - Connection to 00:a0:57:1e:39:49 completed [id=0 id_str=]

**Comment by vanhoefm** [comment]
You need to run a second AP that supports 802.11r, and then use wpa_cli to roam to the second AP so the FT handshake is executed.
