### ISSUE TITLE
Can i run Krack attack with wireless adapter ALFA Network AWUS036NH??

### ISSUE THREAD

**Issue by Arcai666333999** [vanhoefm/krackattacks-scripts#74]
Hello, I've want to ask information about ALFA Network AWUS036NH, can I run Krack-Attack-Script with ALFA Network AWUS036NH???
In this wireless adapter, i have already installed driver rt2800usb, the chipset is ralink technology RT2870/RT3070.
Thanks for your help.

**Comment by kaldubin** [comment]
This is a very late response but yes you can. I hope you made it.
This message is for future users of ALFA AWUS 036NH card who have the same question.
Just follow the instruction and don't forget to run : 
rfkill unblock wifi

**Comment by vanhoefm** [comment]
Thanks for the feedback @kaldubin !
