### ISSUE TITLE
Fail to RESEND_M1

### ISSUE THREAD

**Issue by frog1224** [vanhoefm/krackattacks-scripts#76]
Hi:
    Sometimes my test machine RX deauth frame.

Hostapd got disconnected. (I saw AP-STA-DISCONNECTED message)

But python script didn't get deauth frame from the monitor interface.

I also enabled wireshark capturing packets on the same monitor interface at the same test machine.

I do see deauth frame received in wireshark. (It match what hostapd message "AP-STA-DISCONNECTED")

But python script didn't get it. 

So would encounter RESEND_M1 fail when calling hostapd_cmd and exit.

Any idea to debug or improve?

**Comment by frog1224** [comment]
I tried it on two of my machine.
Both have the same issue.
It rarely happen. But it would happend.

**Comment by vanhoefm** [comment]
I'm not sure why this is happening. If this problem still persists, for you or others reading this, please provide the wireless network cards you are using and which operating systems you are using.
