### ISSUE TITLE
Fatal error while trying to run ./build.sh

### ISSUE THREAD

**Issue by bilirubina** [vanhoefm/krackattacks-scripts#81]
Trying to compile the modified hostapd instance inside the krackattack folder, I get this error:
`fatal: No annotated tags can describe `

followed by a what looks like a hash of 39 characters, and this message
`However, there were annotated tags: try --tags.`

I tried the --tags command, but the output was just like the one above, same error.
What could it be?

**Comment by vanhoefm** [comment]
Can you try using the latest commit?

**Comment by vanhoefm** [comment]
Closing due to no further response.
