### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by weenpeen** [vanhoefm/krackattacks-scripts#82]
I followed the README and I am trying to test access point vulnerabilities. I am using Kali linux VM with a TL-WN722N NIC Card and I am testing the vulnerability on a Linksys WRT54GL wireless router. When I run `sudo wpa_supplicant -D nl80211 -i wlan0 -c network.conf` it says `Successfully initialized wpa_supplicant`, but when I run the command with the ./krack-ft-test.py I get this error. I was successfully able to get everything working up to this point, however Crypto is not found.

```
sudo ./krack-ft-test.py wpa_supplicant -D nl80211 -i wlan0 -c network.conf

Traceback (most recent call last):
  File "/home/user/krackattacks-scripts/krackattack/./krack-ft-test.py", line 11, in <module>
    from libwifi import *
  File "/home/user/krackattacks-scripts/krackattack/libwifi/__init__.py", line 1, in <module>
    from .wifi import *
  File "/home/user/krackattacks-scripts/krackattack/libwifi/wifi.py", line 6, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

```

**Comment by Keskebeu** [comment]
Pip install pycrypto
Pip install crypto

If you have installed everything try uninstalling them first same command
just uninstall instead. Always Run pip without sudo privileges.

Good luck.

**Comment by weenpeen** [comment]
Thanks for the early response, I ran the commands you suggested as the normal user privileges. I received the same exact error. I uninstalled/reinstalled & restarted my Kali machine and still received the same error. Do you have any other suggestions to for where I might have done something wrong? This is the output of `./pysetup.sh` when I created the virtualenv before I ran the script if it is useful. It appears to have built it correctly with `pycryptodome-3.9.9` the dependency installed but the script still has issues with it.

```
./pysetup.sh 

Collecting wheel
  Downloading wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel
Successfully installed wheel-0.36.2
Collecting pycryptodome==3.9.9
  Downloading pycryptodome-3.9.9-cp39-cp39-manylinux1_x86_64.whl (13.7 MB)
     |████████████████████████████████| 13.7 MB 3.7 MB/s 
Collecting scapy==2.4.4
  Downloading scapy-2.4.4.tar.gz (1.0 MB)
     |████████████████████████████████| 1.0 MB 13.7 MB/s 
Building wheels for collected packages: scapy
  Building wheel for scapy (setup.py) ... done
  Created wheel for scapy: filename=scapy-2.4.4-py2.py3-none-any.whl size=1189186 sha256=bc055e3007026288f863a0331fe0aa8c7b542c4a615bd86b350668ce7a64c16d
  Stored in directory: /root/.cache/pip/wheels/e1/75/24/71f33b6a90cc3008c0b0f5a179e9a11aa92870c5a3f61eb5ab
Successfully built scapy
Installing collected packages: scapy, pycryptodome
Successfully installed pycryptodome-3.9.9 scapy-2.4.4
```

**Comment by Keskebeu** [comment]
Are you running the scripts in virtual environment?

**Comment by weenpeen** [comment]
I run `source venv/bin/activate` each time I open a new terminal instance as root. I am running the scripts in `krackattack-scripts/krackattack` directory because that is where the `krack-ft-test.py` and `network.conf` files are located. I am I missing a step to give my script access to the virtual environment? I am also running all of these commands in the Linux terminal, not the python terminal because they are Linux syntax.

**Comment by Keskebeu** [comment]
You are running them correctly.

Run the following:

python3 -c "import sys; print(sys.path)"

**Comment by Keskebeu** [comment]
Once you are in krackattack as root
do

source venv/bin/activate

pip install -r requirements.txt

And than run the script again.


Give it a shot.

**Comment by Keskebeu** [comment]
also do.

pip install Crypto

Good luck

**Comment by weenpeen** [comment]
Thanks for the help, I ran these commands and they were all already installed. running `python3 -c "import sys; print(sys.path)"` did not not change the error. I then tried to run `./krack-ft-test.py wpa_supplicant -D nl80211 -i wlan0 -c network.conf` without the `sudo` because I realized it does not matter because I was already the root user. That worked. I forgot that running commands with `sudo` sometimes makes the command forget environment variables so that might have been the issue. I feel silly.

**Comment by Keskebeu** [comment]
That was not meant to fix your error. I was trying to see if your python
path is where its supposed to be.

**Comment by weenpeen** [comment]
My Python path is:

`['', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/home/matthew/.local/lib/python3.9/site-packages', '/usr/local/lib/python3.9/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.9/dist-packages']`

But I believe I fixed the issue by just running the command as root user and subtracting the `sudo` portion of the command. I was using `sudo` because the instructions told me to but that was the cause of my issue apparently.

**Comment by Keskebeu** [comment]
Makes sense.

You used sudo while root. Take care. You may close the issue.

**Comment by vanhoefm** [comment]
Thanks for the discussion. I've updated the README to hopefully avoid others having the issue in the future. The recommend way is to create the python virtual environment using `./pysetup.sh` and then loading it using:

     sudo su
     source venv/bin/activate
