### ISSUE TITLE
fatal error: stdlib.h: No such file or directory

### ISSUE THREAD

**Issue by ghost** [vanhoefm/krackattacks-scripts#85]
Trying to build the scripts, but when executing build.sh I'm getting:

```/root/krackattacks-scripts/src/utils/includes.h:19:10: fatal error: stdlib.h: No such file or directory```

I'm using a Kali VM, tried to upgrade all packages, reverted to previous snapshot, Googled the problem, no idea.

**Comment by vanhoefm** [comment]
Instead of executing `./build.sh` can you try the following:

```
cd hostapd/
make clean
cp defconfig .config
make
```

If that doesn't work try reinstalling Kali (perhaps you have missing files / dependencies).

**Comment by vanhoefm** [comment]
Closed due to no further response.
