### ISSUE TITLE
krack wpa2 issue

### ISSUE THREAD

**Issue by m0d3st3** [vanhoefm/krackattacks-scripts#86]
Hey Vanhoefm,
I am having an issue while configuring krack in my kali.
I have done all the requirement by I do not know where the error resides
Below are screenshots
Thanks
![1tb](https://user-images.githubusercontent.com/83771852/121876680-132cc400-cd0a-11eb-940b-3cdb6265ec71.PNG)
![2tb](https://user-images.githubusercontent.com/83771852/121876688-158f1e00-cd0a-11eb-9aac-73fdfb704f90.PNG)

**Comment by vanhoefm** [comment]
Does your network card support AP mode? Execute `iw list`. Under "Supported interface modes" it should show "AP", otherwise your network card is not supported.

**Comment by m0d3st3** [comment]
This is the output of my iw list command
![4tb](https://user-images.githubusercontent.com/83771852/121917940-df679380-cd35-11eb-9dd4-c22ba18c240e.PNG)

**Comment by vanhoefm** [comment]
Your network card is not supported. You'll have to find a different one.

PS: Please don't repeatedly close and open an issue.
